### ISSUE TITLE
Dynamic domain selection

### ISSUE THREAD

**Issue by karrots** [karrots/ROS-DDNS#1]
Search for which network a IP lives in and use the locally configured domain. Fall back to default if no domain is configured for selected network.

**Comment by daven-que** [comment]
how about this mod?
[DDNS-DHCP.rsc.txt](https://github.com/karrots/ROS-DDNS/files/713158/DDNS-DHCP.rsc.txt)

**Comment by karrots** [comment]
I'll give this a try. Would you mind submitting your change as a PR against my repo?

**Comment by daven-que** [comment]
Sure, I'll submit a PR this weekend.

I did a fork already, can you pull from it directly?  I'm new to git as
well...

**Comment by daven-que** [comment]
I would have thought that I could attach an issue to the pull request, or attach the pull request to this issue, but that didn't happen.  PR is here https://github.com/karrots/ROS-DDNS/pull/3

**Comment by karrots** [comment]
Closed by e83304ab3b821dc68ba1a54f31f287ddbd611557
